version: '3.8'

services:
  golang-app:
    build: .
    container_name: golang-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'jaritmas'
      MYSQL_USER: 'korie'
      MYSQL_PASSWORD: 'korie123'
      MYSQL_ROOT_PASSWORD: 'korie123'
    volumes:
      - ./dump/backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  mysql-data:
